# 1st day of ml
## 数据预处理

1.导入需要的库

In [144]:
import numpy as np
import pandas as pd

2.导入数据集

In [145]:
dataset = pd.read_csv('Data.csv')

In [146]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [147]:
X = dataset.iloc[:, :-1].values

In [148]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [149]:
Y = dataset.iloc[ : ,3].values

In [150]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

3.处理丢失数据

In [151]:
from sklearn.preprocessing import Imputer

sklearn是基于Python的机器学习库，可想而知，以后还会经常用到，这个句子非常基础，调用的函数是Imputer。

In [152]:
imputer = Imputer(missing_values="NaN",strategy="mean",axis = 0)

Imputer的作用是处理缺失值，第一个参数是要填补的缺失值类型，默认值为"NaN"，strategy参数的默认值是mean，也就是平均值，其他值为median中位数和most_frequent也就是众数，axis = 0代表沿着列进行操作，反之 =1代表沿着行进行。

In [153]:
imputer = imputer.fit(X[ : ,1:3])

fit方法的作用是对X应用刚才的imputer类,但这个操作并不改变X的值，在这里使用的是列方向上的平均值

In [154]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [155]:
X[ : , 1:3] = imputer.transform(X[ : , 1:3])

transform才真正将缺省值按照预先设置好的方法进行赋值

In [156]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

4.解析分类数据

In [157]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [158]:
labelencoder_X = LabelEncoder()

In [159]:
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

LabelEncoder的作用是将指定位置的列进行连续编码，将不易计算的字符串用数字表示，在这里是将第一列进行编码，依据是首字母顺序。


In [160]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [161]:
onehotencoder = OneHotEncoder(categorical_features = [0])

In [162]:
X = onehotencoder.fit_transform(X).toarray()

简单的labelencoder在这里将数据划分成了0至1的数字，但是在实际计算中这还不够，我们需要创建虚拟数据只用0和1来表示不同的数据onehotencoder的使用在这里的作用就是如此。

In [163]:
labelencoder_Y = LabelEncoder()

In [164]:
Y =  labelencoder_Y.fit_transform(Y)

In [165]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

5.切分数据集为训练集合和测试集合

In [166]:
from sklearn.model_selection import train_test_split

Python有专门的用来拆分数据的函数train_test_split

In [167]:
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

In [168]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [169]:
X_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

在这里将X和Y进行分割，分为四个数据集，test_size指定测试集占比，random_state默认为零，代表生成随机数的方法

6.特征向量化

In [170]:
from sklearn.preprocessing import StandardScaler

因为不同数据的取值范围可能非常不同，使得取值范围大的变量权值很大，所以需要进行特征缩放。

In [171]:
sc_X = StandardScaler()

In [172]:
X_train = sc_X.fit_transform(X_train)

In [173]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [174]:
X_test = sc_X.transform(X_test)

In [175]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])